- JudoKitObjC.xcodeproj/project.pbxproj
- Source/JudoKit.h
- Source/JudoKit.m
- Source/JudoKitObjC.h
adding judopayviewcontroller to public headers and exposing it through the judoKit session object
> adding judopayviewcontroller to public headers

- CHANGELOG.md
- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/ViewController.m
- JudoKitObjCExampleAppUITests/JudoKit3DSPaymentTests.swift
- JudoKitObjCExampleAppUITests/JudoKitAVSPaymentTests.swift
- JudoKitObjCExampleAppUITests/JudoKitPaymentDeclinedTests.swift
- JudoKitObjCExampleAppUITests/JudoKitPaymentTests.swift
- JudoKitObjCExampleAppUITests/JudoKitTokenPaymentTests.swift
- JudoKitObjCExampleAppUITests/JudoKitUIDedupTests.swift
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VoidTransactionTests.swift
- UI and Integration tests for dedup.
- Camel case for 'ID'.
> more tests

- Source/Extensions/NSError+Judo.h
- Source/Extensions/NSError+Judo.m
- Source/JudoKit.m
- Tests/APITests/ErrorMessageContentsTests.swift
Implemented Jailbroken method and tests
> Feature branch

- JudoKitObjCExampleApp/DetailViewController.m
- JudoKitObjCExampleApp/ViewController.m
- README.md
- Source/API/JPPayment.m
- Source/JudoKit.h
small fixes to receipt page and hardcoded version of sdk
> small fixes to receipt page and hardcoded version of sdk

- Source/JudoKit.h
- Source/JudoKit.m
- Source/Model/JPReference.h
bug fix for setting payment reference.
> bug fix in setting payment reference

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/ApplePayManager.h
- Source/JudoKitObjC.h
- Tests/APITests/ApplePayTests.swift
Added unit tests for ApplePayConfiguration and ApplePayManager
> Apple Pay Integration [Unit Tests]

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/DetailViewController.h
- JudoKitObjCExampleApp/DetailViewController.m
- JudoKitObjCExampleApp/DetailViewController.xib
- JudoKitObjCExampleApp/ExampleAppCredentials.h
- JudoKitObjCExampleApp/ViewController.m
- Source/ApplePayManager.h
- Source/JudoKitObjC.h
- Source/MockJPTransactionData.json
- Tests/APITests/ApplePayTests.swift
- View Controller has been updated to reflect changes and showcase usage;
- Details View Controller now shows a summary of the returned billing / shipping info if set;
- Details View Controller's constraints have been replaced with stack views;
- A mock JPTransactionData dictionary was added to initialize the mocked JPResponse object;
> Apple Pay Integration [Example App]

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/DetailViewController.h
- JudoKitObjCExampleApp/DetailViewController.m
- JudoKitObjCExampleApp/DetailViewController.xib
- JudoKitObjCExampleApp/ExampleAppCredentials.h
- JudoKitObjCExampleApp/ViewController.m
- Source/ApplePayConfiguration.h
- Source/ApplePayConfiguration.m
- Source/ApplePayManager.h
- Source/ApplePayManager.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/JudoKitObjC.h
- Source/MockJPTransactionData.json
- Source/Model/JPResponse.h
- Tests/APITests/ApplePayTests.swift
- Added Apple Pay configuration file responsible for setting the payment parameters;
- Added Apple Pay manager file that uses the configuration to generate a PKAuthorizationViewController;
> Apple Pay Integration  [Configuration and Manager]

- Source/API/JPTransaction.m
- Added ApplePay metadata to the JPTransaction object;
> Enrich the payments / preauths requests with ApplePay metadata

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
- Fixed, formatted and re-enabled Transaction Enricher and Void Transaction tests;
- Visa Checkout tests are currently disabled due to API issues;
> [Unit Test Improvement & Fixes] Transaction Enricher, Visa Checkout & Void Transactions

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/SaveCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
- Fixed, formatted and re-enabled Register Card, Token Payment & PreAuth tests;
> [Unit Test Improvement & Fixes] Register Card, Token Payment & PreAuth

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/SaveCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
Fixed, formatted and re-enabled Payment and PreAuth unit tests;
> [Unit Test Improvement & Fixes] Payment & PreAuth

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/ErrorMessageContentsTests.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/SaveCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
Fixed, formatted and re-enabled Duplication and Error messages unit tests;
> [Unit Test Improvement & Fixes] Duplication & Error Messages

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/ApplePayTests.swift
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/ErrorMessageContentsTests.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/SaveCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
Fixed, formatted and re-enabled Card Details and Collection unit tests;
> [Unit Test Improvement & Fixes] Card Details & Collection

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- Source/ApplePayManager.m
- Tests/APITests/ApplePayTests.swift
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CardDetailsSetTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/DedupTestCase.swift
- Tests/APITests/ErrorMessageContentsTests.swift
- Tests/APITests/JudoTestCase.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/ReceiptTests.swift
- Tests/APITests/RefundTests.swift
- Tests/APITests/RegisterCardTests.swift
- Tests/APITests/SaveCardTests.swift
- Tests/APITests/TokenPaymentTests.swift
- Tests/APITests/TokenPreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/APITests/TransactionTests.swift
- Tests/APITests/VCOTests.swift
- Tests/APITests/VoidTransactionTests.swift
- Tests/JudoTestCaseConfig.swift
- Fixed, formatted and re-enabled Authentication tests;
- Replaced some redundant tests with new ones;
- Added test token, secret and judo ID;
> [Unit Test Improvement & Fixes] Authentication

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjCExampleApp.xcscheme
- JudoKitObjCExampleApp/ViewController.m
- Source/ApplePayManager.m
- Source/Controller/JudoPayViewController.m
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/Extensions/NSError+Judo.m
- Source/Extensions/NSString+Card.m
- Source/Extensions/NSString+Localize.h
- Source/Extensions/NSString+Localize.m
- Source/Theme/JPTheme.m
- Source/View/InputFields/BillingCountryInputField.m
- Source/View/InputFields/CardInputField.m
- Source/View/InputFields/DateInputField.m
- Source/View/InputFields/IssueNumberInputField.m
- Source/View/InputFields/PostCodeInputField.m
- Source/View/InputFields/SecurityCodeInputField.m
- Source/View/LoadingView.m
- de.lproj/Localizable.strings
- en.lproj/Localizable.strings
- es.lproj/Localizable.strings
- fr.lproj/Localizable.strings
- nl.lproj/Localizable.strings
- pt-PT.lproj/Localizable.strings
Added Locale Labels to do the UI Components
> EP-104 Localization

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjCExampleApp.xcscheme
- Source/API/JPSession.m
- Source/API/JPTransaction.h
- Source/API/JPTransaction.m
- Source/Controller/JudoPayViewController.m
- Source/View/JP3DSWebView.h
- Changed UIWebView to WKWebView
> WKWebView Update

- Source/API/JPTransactionEnricher.m
> EP-177 Multiple requests fix

- JudoKitObjCExampleApp/ViewController.m
- Source/Managers/ApplePayManager.m
- Source/Model/ApplePay/ApplePayWrappers.h
- Source/Model/ApplePay/ApplePayWrappers.m
- Fixed crashing issue due to missing required fields for PKShippingMethod;
> PKShippingMethod Crash Fix

- Source/JudoKit.m
- Set the `activeViewController` property inside the `invokePayment` method;
> [Improvement] Back Button issue fix

- JudoKitObjC.podspec
- Source/Info.plist
- Source/JudoKit.h
> [Improvement] Version 8.0.1 update

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/DetailViewController.m
- JudoKitObjCExampleApp/DetailViewController.xib
- JudoKitObjCExampleApp/DetailsTableViewController.h
- JudoKitObjCExampleApp/DetailsTableViewController.m
- JudoKitObjCExampleAppUITests/JudoKitCardDetailsTests.swift
- Source/API/JPSession.m
- Source/API/JPTransaction.m
- Source/API/JPTransactionEnricher.m
- Source/Controller/JudoPayViewController.m
- Source/Extensions/NSBundle+Additions.h
- Source/Extensions/NSBundle+Additions.m
- Source/Extensions/NSString+Localize.h
- Source/Managers/ApplePayManager.m
- Source/Model/ApplePay/ApplePayWrappers.h
- Source/Model/ApplePay/ApplePayWrappers.m
- Source/Model/JPCardDetails.h
- Source/Model/JPCardDetails.m
- Enhanced card details model with bank, cardCategory, cardCountry, cardFunding, cardScheme fields
- Using API version 5.6.0
> Enhanced card details model

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/Model/IDEALBank.h
- Source/Model/IDEALBank.m
Created an iDEAL bank object that exposes the bank name and bank identifier code based on the bank type provided.
> [iDEAL] Added the iDEAL bank models

- Source/Controller/JudoPayViewController.m
- Added safe insets the Payment Button
> Payment Button Safe Insets

- Source/Controller/JudoPayViewController.m
Reverted back to previous JudoViewController;
Made sure the button looks good on simulators;
> [Bugfix] Safe Area Bottom

- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/API/JPCheckCard.h
- Source/API/JPTransaction.m
- Source/Extensions/JPTheme+Additions.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Model/JPTransactionData.h
- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
Added the `invokeCheckCard` method to the SDK that shows the pre-build UI;
> [Check Card] Pre-Build UI

- JudoKitObjC.xcodeproj/project.pbxproj
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/API/JPCheckCard.h
- Source/API/JPCheckCard.m
- Source/API/JPTransaction.m
- Source/Extensions/JPTheme+Additions.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Model/JPTransactionData.h
- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
- Added the 'checkCard' method to the Judo SDK;
- Added the JPCheckCard object;
> [Check Card] Added method and JPCheckCard object

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/Managers/IDEALManager.h
- Source/Managers/IDEALManager.m
- Source/iDEAL/IDEALFormViewController.m
- Tests/APITests/IDEALManagerTests.swift
- Tests/JudoKitObjCTests-Bridging-Header.h
Added unit tests for IDEALManager
> [iDEAL] Unit Tests

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/API/JPSession.m
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/Extensions/NSError+Judo.m
- Source/JPReachability.h
- Source/JPReachability.m
- Source/JudoKit.m
- Source/Managers/IDEALManager.h
- Source/Managers/IDEALManager.m
- Source/Model/IDEALBank.m
- Source/Model/JPOrderDetails.m
- Source/Model/JPTransactionData.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/Cells/IDEALBankTableViewCell.m
- Source/iDEAL/IDEALBankSelectionTableViewController.h
- Source/iDEAL/IDEALBankSelectionTableViewController.m
- Source/iDEAL/IDEALFormViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Tests/APITests/IDEALManagerTests.swift
- Tests/JudoKitObjCTests-Bridging-Header.h
Ran a `sh ./clang-format.sh` command
> [Improvement] CLang Formatting

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/API/JPSession.m
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/Extensions/NSError+Judo.m
- Source/JPReachability.h
- Source/JPReachability.m
- Source/JudoKit.m
- Source/Managers/IDEALManager.h
- Source/Managers/IDEALManager.m
- Source/Model/IDEALBank.m
- Source/Model/JPOrderDetails.m
- Source/Model/JPTransactionData.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/Cells/IDEALBankTableViewCell.m
- Source/iDEAL/IDEALBankSelectionTableViewController.h
- Source/iDEAL/IDEALBankSelectionTableViewController.m
- Source/iDEAL/IDEALFormViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Tests/APITests/IDEALManagerTests.swift
- Tests/JudoKitObjCTests-Bridging-Header.h
- Added retry button to the TransactionStatus view;
- Retry button tap handled by IDEALFormViewController;
- Calls `startPoolingStatus` again;
> [iDEAL] Retry failed transaction

- Source/Model/IDEALBank.h
- Source/Model/IDEALBank.m
- Source/iDEAL/IDEALBankSelectionTableViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Added ability to store selected bank into user defaults;
> [iDEAL] Save bank choice

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleAppUITests/JudoKitIDEALTransactionTests.swift
- Source/Model/IDEALBank.h
- Source/Model/IDEALBank.m
- Source/iDEAL/Cells/IDEALBankTableViewCell.xib
- Source/iDEAL/IDEALBankSelectionTableViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Added UI Tests for the iDEAL Transaction form
> [iDEAL] iDEAL Form UI Tests

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/API/JPSession.m
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/Extensions/NSError+Judo.m
- Source/JPReachability.h
- Source/JPReachability.m
- Source/JudoKit.m
- Source/Managers/IDEALManager.h
- Source/Managers/IDEALManager.m
- Source/Model/IDEALBank.m
- Source/Model/JPOrderDetails.m
- Source/Model/JPTransactionData.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/Cells/IDEALBankTableViewCell.m
- Source/iDEAL/IDEALBankSelectionTableViewController.h
- Source/iDEAL/IDEALBankSelectionTableViewController.m
- Source/iDEAL/IDEALFormViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Tests/APITests/IDEALManagerTests.swift
- Tests/JudoKitObjCTests-Bridging-Header.h
I've renamed the `pool` methods to `poll` in the `feature/retry-button` commit.
> [Improvement] Better polling handling

- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/IDEALBankSelectionTableViewController.m
- Source/iDEAL/IDEALFormViewController.m
- Added full customizability to iDEAL flow via JPTheme objects
- Made the name field mandatory
> [EP-341] iDEAL Payment View Theming

- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/Managers/IDEALService.h
- Source/Managers/IDEALService.m
- Source/Model/JPOrderDetails.h
- Source/Model/JPTransactionData.h
- Source/Model/JPTransactionData.m
- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/IDEALBankSelectionTableViewController.m
- Source/iDEAL/IDEALFormViewController.m
Mapped the IDEAL status response fields based on A/C
> [EP-343] iDEAL Transaction Response Mapping

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/Controllers/MainViewController.m
- Source/API/JPReceipt.m
- Source/API/JPSession.h
- Source/API/JPSession.m
- Source/API/JPTransaction.m
- Source/API/JPTransactionProcess.m
- Source/Controller/JudoPaymentMethodsViewController.h
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Managers/IDEALService.h
- Source/Managers/IDEALService.m
- Source/Theme/JPTheme.m
- Source/iDEAL/IDEALFormViewController.h
- Source/iDEAL/IDEALFormViewController.m
iDEAL Transaction Response can be obtained by a user through a delegate method
> [EP-347] Add Callback Details to iDEAL Transaction Request

- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
- Source/View/TransactionStatusView.m
- Source/iDEAL/IDEALFormViewController.m
- More detailed customization for navigation bar elements;
- Added customization of the floating label of the input field;
> [iDEAL] Even more customization options

- JudoKitObjC.podspec
- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/Controllers/MainViewController.m
- Source/Controller/JudoPayViewController.m
- Source/Info.plist
- Source/JudoKit.h
- Source/View/JP3DSWebView.m
**Includes:**
- Payment Button inset fix;
- 3D Security fix;
> Merged master into develop

- JudoKitObjCExampleApp/Controllers/MainViewController.m
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/Managers/IDEALService.h
- Source/Managers/IDEALService.m
- Source/Theme/JPTheme.h
- Source/Theme/JPTheme.m
- Source/View/TransactionStatusView.h
- Source/View/TransactionStatusView.m
- Source/iDEAL/IDEALFormViewController.m
> [iDEAL] New retry logic

- Source/Controller/JudoPayViewController.m
> Remove PaRes field and button from the sandbox 3D secure flow

- Source/Controller/JudoPayViewController.h
- Source/Controller/JudoPayViewController.m
- Source/Controller/JudoPaymentMethodsViewController.m
- fixed Error missing on Card Modal overlay when swiping down
> EP 463 - BUG - Error missing on Card Modal overlay when swiping down

- Source/iDEAL/IDEALFormViewController.m
Fixed scrolling issues with iDEAL web navigation
> iDEAL Scrolling Fix

- Source/Modules/PaymentMethods/View/Subviews/Cells/CardCell/JPPaymentMethodsCardCell.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/CardListFooterCell/JPPaymentMethodsCardListFooterCell.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/CardListHeaderCell/JPPaymentMethodsCardListHeaderCell.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/EmptyCardListCell/JPPaymentMethodsEmptyCardListCell.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/PaymentMethodSelectionCell/JPPaymentMethodsSelectionCell.m
- Source/Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsCardHeaderView.m
- Source/Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsEmptyHeaderView.m
- Source/Modules/PaymentMethods/View/Subviews/JPPaymentMethodsHeaderView.m
Added missing background and text colors
> [Bugfix] JPPaymentMethodView dark mode fixes

- Source/Helpers/Functions.h
- Source/Helpers/Functions.m
- Source/Modules/PaymentMethods/View/JPPaymentMethodsView.m
- Source/Modules/PaymentMethods/View/JPPaymentMethodsViewController.m
- Source/Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsCardHeaderView.m
Fixed card view clipping due to different aspect ratios
> [Bugfix] Card View Aspect Ratio

- Source/Controller/JudoPayViewController.m
Disabled WKWebView zooming on the 3DSecure screen
> [Bugfix] Disabled 3DS zoom

- JudoKitObjC.podspec
- Podfile
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/Modules/AddCard/Interactor/JPAddCardInteractor.h
- Source/Modules/AddCard/Interactor/JPAddCardInteractor.m
- Source/Modules/AddCard/Presenter/JPAddCardPresenter.m
- Source/Modules/AddCard/View/JPAddCardViewController.h
- Source/Modules/AddCard/View/JPAddCardViewController.m
- Source/Modules/PaymentMethods/View/JPPaymentMethodsView.m
- Source/Modules/PaymentMethods/View/JPPaymentMethodsViewController.m
- Source/Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsCardHeaderView.m
- Source/Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsEmptyHeaderView.m
- Source/ScanCardViewController/JPScanCardViewController.m
Added camera permissions check to the scan card flow
> [Scan Card] Camera Permissions

- JudoKitObjCExampleAppUITests/JudoKitPaymentMethodsTests.swift
- On successful payment, dismiss the payment method selection view;
- On failed payment, display error;
> [EP-534] Card Payment UI Tests

- JudoKitObjCExampleAppUITests/JudoKitPaymentMethodsTests.swift
- Source/Extensions/UIViewController+Additions.m
- Source/Modules/PaymentMethods/View/JPPaymentMethodsViewController.m
- Error alerts are accompanied by navigation feedback haptic effects;
> [EP-534] Added vibration effect on failed requests

- JudoKitObjCExampleAppUITests/JudoKitAddCardTests.swift
- Podfile
- Podfile.lock
- Source/Model/JPConstants.h
- Source/Modules/AddCard/View/Subviews/JPCardNumberField.m
Added Discover validation for Add Card Modal
> [EP-554] - Discovery Card Validation

- JudoKitObjCExampleAppUITests/JudoKitPaymentMethodsTests.swift
- Tests/APITests/ApplePayTests.swift
- added ui tests for card deletion feature
> Delete Cards UI tests

- JudoKitObjCExampleAppUITests/JudoKitPaymentMethodsTests.swift
- Resources/de.lproj/Localizable.strings
- Resources/en.lproj/Localizable.strings
- Resources/es.lproj/Localizable.strings
- Resources/fr.lproj/Localizable.strings
- Resources/nl.lproj/Localizable.strings
- Resources/pt-PT.lproj/Localizable.strings
- Source/Model/JPCardStorage.h
- Source/Model/JPCardStorage.m
- Source/Modules/AddCard/Presenter/JPAddCardPresenter.h
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.h
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
- Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.h
- Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
- Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsViewModel.h
- Source/Modules/PaymentMethods/View/JPPaymentMethodsViewController.h
- Source/Modules/PaymentMethods/View/JPPaymentMethodsViewController.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/CardCell/JPPaymentMethodsCardCell.m
- Source/Modules/PaymentMethods/View/Subviews/Cells/CardListHeaderCell/JPPaymentMethodsCardListHeaderCell.h
- Source/Modules/PaymentMethods/View/Subviews/Cells/CardListHeaderCell/JPPaymentMethodsCardListHeaderCell.m
- Source/Services/JPCardValidationService.m
- Tests/APITests/ApplePayTests.swift
Implemented Delete Cards feature
> [EP-560] Card Selector - Delete Cards

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/Controllers/MainViewController.m
- Source/JPPaymentMethod.h
- Source/JPPaymentMethod.m
- Source/JPSectionView.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Modules/PaymentMethods/Builder/JPPaymentMethodsBuilder.h
- Source/Modules/PaymentMethods/Builder/JPPaymentMethodsBuilder.m
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.h
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
- Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
- Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsViewModel.h
- Source/Modules/PaymentMethods/View/Subviews/Cells/PaymentMethodSelectionCell/JPPaymentMethodsSelectionCell.m
Added ability to configure preferred payment methods via the Judo SDK
> [EP-531] Payment Method Selection via Judo SDK

- Source/View/JPTextField.h
- Source/View/JPTextField.m
Fixed a bug with app crashing when input is added via voiceover
> [Bugfix] Voiceover Crash

- Resources/en.lproj/Localizable.strings
- Source/Modules/AddCard/Presenter/JPAddCardPresenter.m
- Source/Modules/AddCard/View/JPAddCardViewController.h
- Source/Modules/AddCard/View/JPAddCardViewController.m
- Added  Card Modal Amendments
> [EP-592] - Add Card Modal Amendments

- JudoKitObjCExampleApp/Controllers/MainViewController.m
- Source/Controller/JudoPaymentMethodsViewController.m
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Managers/IDEALService.h
- Source/Managers/IDEALService.m
- Source/iDEAL/IDEALFormViewController.h
- Source/iDEAL/IDEALFormViewController.m
- Changed iDEAL transaction amount type from `double` to `JPAmount`
> [Bugfix] iDEAL Amount

- Source/View/FloatingTextField/JPFloatingTextField.m
Fixed a layout constraint issue when JPFloatingTextfield displays an inline error
> JPFloatingTextfield constraint error fix

- Source/Extensions/UIFont/UIFont+Additions.h
- Source/Extensions/UIFont/UIFont+Additions.m
- Source/Models/CardPattern/JPCardPattern.m
- Source/Modules/PaymentMethods/View/Subviews/CardView/JPCardPaymentMethodView.m
> Added better support for iPhone SE devices

- Source/Modules/CardCustomization/View/Cells/CardCustomizationTextInputCell/JPCardCustomizationTextInputCell.m
- Source/View/InputField/JPInputField.h
- Source/View/InputField/JPInputField.m
- Change the keyboard's return key to `Done`;
- Added dismiss on Return key tap;
> Card Customization keyboard dismissal

- Source/Modules/PaymentMethods/View/Subviews/Cells/CardCell/JPPaymentMethodsCardCell.m
fixed red color title showing for not expired cards
> expiry title color bugfix

- JudoKitObjC.xcodeproj/project.pbxproj
- Source/Modules/Transaction/Interactor/JPTransactionInteractor.h
- Source/Modules/Transaction/Interactor/JPTransactionInteractor.m
- Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
- Source/Modules/Transaction/View/JPTransactionViewController.m
- Source/Services/CardValidation/JPCardValidationService.h
- Source/Services/CardValidation/JPCardValidationService.m
- Fixed the keyboard issue after Scan Card completes;
- Fixed the input fields not updating with the Scan Card results if they are already populated;
> Scan card fixes

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/AppDelegate.h
- JudoKitObjCExampleApp/Controllers/Main/MainViewController.m
- Source/Models/Address/JPAddress.h
- Source/Models/Address/JPAddress.m
- Source/Models/Configuration/JPConfiguration.h
- Source/Modules/Transaction/Interactor/JPTransactionInteractor.h
- Source/Modules/Transaction/Interactor/JPTransactionInteractor.m
- Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
> Added configurable card address

- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjCExampleApp.xcscheme
- JudoKitObjCExampleApp/Controllers/MainViewController.m
- JudoKitObjCExampleAppUITests/JudoKitCardDetailsTests.swift
- JudoKitObjCExampleAppUITests/JudoKitIDEALTransactionTests.swift
- JudoKitObjCExampleAppUITests/JudoKitMaestroTests.swift
- JudoKitObjCExampleAppUITests/JudoKitTokenPaymentTests.swift
- Source/Extensions/NSError+Judo.h
- Source/iDEAL/Cells/IDEALBankTableViewCell.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/TestsConstants.swift
- Fixed and updated unit tests;
- Fixed and updated UI tests;
- Disabled VCO test since credentials are unknown;
- Removed Singapore currency tests since only GBP is supported in sandbox mode;
- Increased timeout to 60 seconds;
> [Improvement] Updated UI and Unit Tests

- JudoKitObjC.podspec
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjC.xcscheme
- JudoKitObjC.xcodeproj/xcshareddata/xcschemes/JudoKitObjCExampleApp.xcscheme
- JudoKitObjCExampleApp/Controllers/MainViewController.m
- JudoKitObjCExampleAppUITests/JudoKitCardDetailsTests.swift
- JudoKitObjCExampleAppUITests/JudoKitIDEALTransactionTests.swift
- JudoKitObjCExampleAppUITests/JudoKitMaestroTests.swift
- JudoKitObjCExampleAppUITests/JudoKitTokenPaymentTests.swift
- README.md
- Source/Extensions/NSError+Judo.h
- Source/Info.plist
- Source/JudoKit.h
- Source/iDEAL/Cells/IDEALBankTableViewCell.m
- Tests/APITests/AuthenticationTests.swift
- Tests/APITests/CollectionTests.swift
- Tests/APITests/PaymentTests.swift
- Tests/APITests/PreAuthTests.swift
- Tests/APITests/TransactionEnricherTests.swift
- Tests/TestsConstants.swift
- Updated version to 10.0.2
- Updated unit tests and UI tests;
- Updated README.md
> [Release] 10.0.2

- JudoKitObjCExampleApp/Controllers/Main/MainViewController.m
- Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
- Source/Services/CardValidation/JPCardValidationService.m
- Source/Services/Transaction/JPTransactionService.m
- Set the amount for Save Card, Register Card and Check Card to 0;
- Set UK as the default selected AVS country field;
- Restrict the user from adding duplicate cards - In Analysis;
- Add swiping behavior to the Payment Method Selector - In Analysis;
https://thedojo.atlassian.net/browse/EP-780
> [EP-780] Payment Widgets Updates

- Source/Models/Address/JPAddress.h
- Source/Models/Address/JPAddress.m
- Source/Models/Constants/JPConstants.h
- Source/Models/Country/JPCountry.h
- Source/Models/Country/JPCountry.m
- Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
replace string type billingCountry with countryCode nsnumber
add country ISO codes to constants
send null for "other" type in api call
> EP-838 [iOS] Refactor CardAddressModel to use the correct countryCode

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/Controllers/Main/MainViewController.m
- JudoKitSwiftExampleApp/ViewControllers/MainViewController.swift
- Source/JudoKit.h
- Source/JudoKit.m
- Source/Models/Constants/JPConstants.h
- Source/Services/ConfigurationValidation/JPConfigurationValidationService.h
- Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
- Tests/Modules/PaymentMethods/Mocks/JPPaymentMethodsInteractorMock.swift
- Tests/Modules/Sevices/JPAppleConfigurationValidationServiceTest.swift
- Tests/Modules/Sevices/JPConfigurationValidationServiceTest.swift
add new validator for configuration
add unit tests for validator
update old tests
update sample project with error handling.
> EP-839 [iOS] Add configuration properties validation

- Source/Models/Address/JPAddress.m
dont send null to backend for other country type
> EP-851  [iOS] Country code iso and null params in api call

- JudoKitObjC.xcodeproj/project.pbxproj
- JudoKitObjCExampleApp/Controllers/Main/MainViewController.m
- JudoKitObjCExampleApp/Models/DemoFeature.h
- JudoKitObjCExampleApp/Models/DemoFeature.m
- JudoKitSwiftExampleApp/Models/DemoFeatureType.swift
- JudoKitSwiftExampleApp/ViewControllers/MainViewController.swift
- Source/Helpers/NSDateFormator/JPFormatters.h
- Source/Helpers/NSDateFormator/JPFormatters.m
- Source/Models/Transaction/JPTransaction.h
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
- Source/Services/ApplePay/JPApplePayService.m
- Source/Services/CardValidation/JPCardValidationService.m
- Tests/Modules/Sevices/PaymentMethod/JPPaymentMethodsInteractorTest.swift
singletone helper for nsdateformat
add server to server payment
> EP-705 iOS - Make a server payment

- Source/Helpers/NSDateFormator/JPFormatters.m
- Source/JudoKit.m
- Source/Models/Address/JPAddress.m
- Source/Models/CardStorage/JPCardStorage.m
- Source/Models/Configuration/JPConfiguration.h
- Source/Models/Configuration/JPConfiguration.m
- Source/Models/Constants/JPConstants.h
- Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
- Source/Services/ApplePay/JPApplePayService.m
- Source/Services/CardValidation/JPCardValidationService.m
- Source/Services/ConfigurationValidation/JPConfigurationValidationService.h
- Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
- Source/Services/Transaction/JPTransactionService.m
- Tests/Modules/Sevices/ConfigurationValidator/JPAppleConfigurationValidationServiceTest.swift
- Tests/Modules/Sevices/ConfigurationValidator/JPConfigurationValidationServiceTest.swift
- changed amount to be nullable in configuration and implemented default amount value for checkCard , saveCard, and RegisterCard
> [EP-842] Check Card, Save Card and Register Card Amounts
